version: '3'
services:
  node:
    build: ./express
    ports:
    - "3000:3000"
  
  redis:
    image: "redis:alpine"
    command: ["redis-server", "--dbfilename", "dump.rdb", "--dir", "/data"]
    volumes:
      - ./redis-data:/data
    ports:
    - "6379:6379"

volumes:
  redis-data:
  